AWSTemplateFormatVersion: 2010-09-09
Description: Alarm and ScalingPolicy template

Parameters:
  QueueName:
    Description: Queue Name
    Type: String
    Default: tst-dva-queue.fifo
  ASGStackName:
    Description: AutoScalingGroup Stack Name
    Type: String
    Default: asg-tutorial-autoscaling

Resources:
  ScaleOutPolicy:
    Type: AWS::AutoScaling::ScalingPolicy
    Properties:
      AdjustmentType: ChangeInCapacity
      PolicyType: SimpleScaling
      Cooldown: 60
      AutoScalingGroupName:
        Fn::ImportValue: !Sub ${ASGStackName}-AutoScalingGroupName
      ScalingAdjustment: 1

  Alarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmDescription: Alarm for comparing the number of messages in SQS and the number of instances in ASG
      Metrics:
        - Id: e1
          Expression: m1-m2
          Label: MessagesAndInstancesFire
        - Id: m1
          MetricStat:
            Metric:
              Namespace: AWS/SQS
              MetricName: ApproximateNumberOfMessagesVisible
              Dimensions:
                - Name: QueueName
                  Value: !Ref QueueName
            Period: 60
            Stat: Average
          ReturnData: false
        - Id: m2
          MetricStat:
            Metric:
              Namespace: AWS/AutoScaling
              MetricName: GroupInServiceInstances
              Dimensions:
                - Name: AutoScalingGroupName
                  Value:
                    Fn::ImportValue: !Sub ${ASGStackName}-AutoScalingGroupName
            Period: 60
            Stat: Average
          ReturnData: false
      EvaluationPeriods: 1
      Threshold: 1
      ComparisonOperator: GreaterThanOrEqualToThreshold
      AlarmActions:
        - !Ref ScaleOutPolicy