AWSTemplateFormatVersion: 2010-09-09
Description: Launch Configuration and AutoScalingGroup Configuration

Parameters:
  Service:
    Description: Service Name
    Type: String
    Default: tst
    AllowedValues:
      - tst
  AccountType:
    Description: Account Type
    Type: String
    Default: dva
    AllowedValues:
      - dva
      - pda
  ECSAMI:
    Description: AMI ID
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
    Default: /aws/service/ecs/optimized-ami/amazon-linux-2/recommended/image_id
  NetworkStackName:
    Description: Stack Relation With NetworkConfiguration Name
    Type: String
    MinLength: 1
    MaxLength: 255
    AllowedPattern: ^[a-zA-z][-a-zA-Z0-9]*$
    Default: asg-tutorial-network-config
  # KeyName:
  #   Description: The EC2 Key Pair to allow SSH access to the instance
  #   Type: AWS::EC2::KeyPair::KeyName
  InstanceMinSize:
    Description: Instance Min Size
    Type: Number
    Default: 0
  InstanceDesiredCapacity:
    Description: Instance Desired Capacity
    Type: Number
    Default: 0
  InstanceMaxSize:
    Description: Instance Max Size
    Type: Number
    Default: 2

Resources:
  # 1. 起動設定を作る
  LaunchConfiguration:
    Type: AWS::AutoScaling::LaunchConfiguration
    Properties:
      AssociatePublicIpAddress: false
      # IamInstanceProfile: !Sub arn:aws:iam::${AWS::AccountId}:instance-profile/ecsInstanceRole
      IamInstanceProfile: !Ref EcsInstanceProfile
      ImageId: !Ref ECSAMI
      InstanceMonitoring: false
      InstanceType: t2.micro
      # KeyName: !Ref KeyName # EC2とSSH接続するために必要
      LaunchConfigurationName: demo-launch-configuration # 起動設定名
      SecurityGroups:
        - Fn::ImportValue: !Sub ${NetworkStackName}-SecurityGroupID
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash -xe
          echo ECS_CLUSTER=${Service}-${AccountType}-cluster >> /etc/ecs/ecs.config

  # 2. AutoScalingGroupを作成する
  AutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      AutoScalingGroupName: demo-autoscaling-group # AutoScalingGroup名
      LaunchConfigurationName: !Ref LaunchConfiguration
      MinSize: !Ref InstanceMinSize
      DesiredCapacity: !Ref InstanceDesiredCapacity
      MaxSize: !Ref InstanceMaxSize
      # NewInstancesProtectedFromScaleIn: true
      Tags:
        - Key: Name
          PropagateAtLaunch: true
          Value: asg-tutorial-ec2 # EC2インスタンスの名前
      VPCZoneIdentifier:
        - Fn::ImportValue: !Sub ${NetworkStackName}-SubnetID-A
        # - Fn::ImportValue: !Sub ${NetworkStackName}-SubnetID-C
      MetricsCollection: # メトリクスを有効化
        - Granularity: 1Minute
          Metrics:
            - GroupInServiceInstances

  EcsInstanceRole:
    Type: AWS::IAM::Role
    Properties:
      Description: Provides EC2 Instance with authorization
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonEC2ContainerServiceforEC2Role
      Path: !Sub /${Service}/
      RoleName: !Sub ${Service}-${AccountType}-ecsInstanceRole
      Tags:
        - Key: Owner
          Value: !Ref Service

  EcsInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: !Sub /${Service}/
      Roles:
        - !Ref EcsInstanceRole

Outputs:
  AutoScalingGroupName:
    Description: AutoScalingGroup Name
    Value: !Ref AutoScalingGroup
    Export:
      Name: !Sub ${Service}-${AccountType}-asg